repos:
 -  repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
 -  repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v7.0.1
    hooks:
    - id: commitlint
      stages: [commit-msg]